### ISSUE TITLE
do u have python version?

### ISSUE THREAD

**Issue by john09282922** [spacewalk01/yolov9-bytetrack-tensorrt#2]
thanks,

**Comment by spacewalk01** [comment]
not yet I will try to include python version. Thanks for asking.

**Comment by spacewalk01** [comment]
Working on python version 👍

**Comment by spacewalk01** [comment]
There you go. I implemented python version: https://github.com/spacewalk01/yolov9-bytetrack-tensorrt/tree/main/python
