### ISSUE TITLE
Nothing happend after yolov9-bytetrack-trt.exe complete

### ISSUE THREAD

**Issue by ffdalimarta** [spacewalk01/yolov9-bytetrack-tensorrt#3]
Hi Spacewalk, this is awesome. I follow the instruction to install and generate all requirements, and everything goes perfect until when I tried to : yolov9-bytetrack-trt.exe yolov9-c.engine switch1.mp4 in my console, it's nothing happened.

Did I missed something here?

PS: I've placed the video file in the same location as the .exe
![Screenshot 2024-02-28 114317](https://github.com/spacewalk01/yolov9-bytetrack-tensorrt/assets/106646922/0307f458-fb18-4a1f-a1b5-dc1652da56f6)

**Comment by spacewalk01** [comment]
make sure that yolov9-c.engine and switch1.mp4 video files are present in Release directory. Or you can use absolute path for these files

**Comment by ffdalimarta** [comment]
I think I missed the yolov9-c.engine file here. Can you show me where can I obtain that file?

**Comment by spacewalk01** [comment]
Sorry it wasn't in the instruction. So added it. You can build the engine using following command:

`trtexec.exe --onnx=yolov9-c-converted.onnx --explicitBatch --saveEngine=yolov9-c.engine --fp16`

trtexec is in the <TensorRT root directory>/bin directory

**Comment by ffdalimarta** [comment]
thank you for the update. I follow your suggestion then using:

`trtexec.exe --onnx=yolov9-c-converted.onnx --explicitBatch --saveEngine=yolov9-c.engine --fp16` 

but there are some problem in the generation of the engine. Did you ever encounter this problem below :

![Screenshot 2024-02-28 122036](https://github.com/spacewalk01/yolov9-bytetrack-tensorrt/assets/106646922/b240da2c-54e4-470e-a564-494a2bdcee69)

_PS: the required **nvinfer_plugin.dll** is the TensorRT/lib folder, and I have added TensorRT/lib location to the PATH, but the error still persist_

**Comment by spacewalk01** [comment]
Set tensorrt installation path in your envornment variable or copy dll to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.x\bin or you can copy it to the folder you are running your exe TensorRT/bin and Your_project/builld/Release
